wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value: []
epochs:
  value: 400
learning_rate:
  value: 0.001070508139979666
num_hiddens:
  value: 16
num_layers:
  value: 8
num_skip_layers:
  value: 1
task:
  value: regression
weight_decay:
  value: 0.006417844427115162
