wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value:
  - 64
epochs:
  value: 400
learning_rate:
  value: 0.00920008367684063
num_hiddens:
  value: 64
num_layers:
  value: 10
num_skip_layers:
  value: 1
task:
  value: regression
weight_decay:
  value: 0.007839908352588652
