wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value: []
epochs:
  value: 400
learning_rate:
  value: 0.000193831321670827
num_hiddens:
  value: 16
num_layers:
  value: 10
num_skip_layers:
  value: 1
task:
  value: regression
weight_decay:
  value: 0.001857830361554705
