wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value: []
epochs:
  value: 400
learning_rate:
  value: 0.0014470638728033285
num_hiddens:
  value: 32
num_layers:
  value: 8
num_skip_layers:
  value: 2
task:
  value: regression
weight_decay:
  value: 0.004134058036874262
