wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value: []
epochs:
  value: 400
learning_rate:
  value: 0.009003970688699058
num_hiddens:
  value: 64
num_layers:
  value: 8
num_skip_layers:
  value: 1
task:
  value: regression
weight_decay:
  value: 0.0014275112150642104
