wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value: []
epochs:
  value: 400
learning_rate:
  value: 0.009711845035840078
num_hiddens:
  value: 64
num_layers:
  value: 6
num_skip_layers:
  value: 2
task:
  value: regression
weight_decay:
  value: 0.00016802956100002967
