wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value:
  - 64
epochs:
  value: 400
learning_rate:
  value: 0.008183883676095433
num_hiddens:
  value: 32
num_layers:
  value: 6
num_skip_layers:
  value: 1
task:
  value: regression
weight_decay:
  value: 0.003653997732844746
