wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value:
  - 64
epochs:
  value: 400
learning_rate:
  value: 0.006641085887920216
num_hiddens:
  value: 64
num_layers:
  value: 8
num_skip_layers:
  value: 2
task:
  value: regression
weight_decay:
  value: 0.008690622823449358
