wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value: []
epochs:
  value: 400
learning_rate:
  value: 0.005127910310454985
num_hiddens:
  value: 16
num_layers:
  value: 8
num_skip_layers:
  value: 2
task:
  value: regression
weight_decay:
  value: 0.007794267630209142
