wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value:
  - 64
epochs:
  value: 400
learning_rate:
  value: 0.008935222086905779
num_hiddens:
  value: 16
num_layers:
  value: 4
num_skip_layers:
  value: 2
task:
  value: regression
weight_decay:
  value: 0.009321665064633024
