wandb_version: 1

aggregation:
  value: max
apply_bn:
  value: true
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
conv_channels:
  value:
  - 32
  - 64
  - 128
encoder_channels:
  value: []
epochs:
  value: 300
learning_rate:
  value: 0.001378067250590932
task:
  value: regression
weight_decay:
  value: 0.004137215229842084
