wandb_version: 1

aggregation:
  value: max
apply_bn:
  value: true
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
conv_channels:
  value:
  - 32
  - 64
  - 128
encoder_channels:
  value: []
epochs:
  value: 300
learning_rate:
  value: 0.003147473151587473
task:
  value: regression
weight_decay:
  value: 0.0024435777933829537
