wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value:
  - 64
epochs:
  value: 800
learning_rate:
  value: 0.008378983777412509
num_hiddens:
  value: 16
num_layers:
  value: 10
num_skip_layers:
  value: 1
task:
  value: classification
weight_decay:
  value: 0.00668949769034409
