wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1675699530.581931
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.8.15
      5: 0.13.9
      8:
      - 5
aggregation:
  desc: null
  value: mean
apply_dropedge:
  desc: null
  value: false
apply_dropout:
  desc: null
  value: true
batch_size:
  desc: null
  value: 32
encoder_channels:
  desc: null
  value:
  - 64
epochs:
  desc: null
  value: 800
learning_rate:
  desc: null
  value: 0.0017666023625511208
num_hiddens:
  desc: null
  value: 32
num_layers:
  desc: null
  value: 8
num_skip_layers:
  desc: null
  value: 2
task:
  desc: null
  value: regression
weight_decay:
  desc: null
  value: 0.0058019954037737236
