wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 16
encoder_channels:
  value:
  - 64
epochs:
  value: 800
learning_rate:
  value: 0.004131330229366228
num_hiddens:
  value: 16
num_layers:
  value: 2
num_skip_layers:
  value: 1
task:
  value: regression
weight_decay:
  value: 0.000128918045897799
