wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1674478756.549965
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.8.15
      5: 0.13.9
      8:
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 200
experiment_name:
  desc: null
  value: height_prediction_5k
learning_rate:
  desc: null
  value: 0.001
print_every_n:
  desc: null
  value: 200
task:
  desc: null
  value: regression
validate_every_n:
  desc: null
  value: 200
