wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1675699245.549764
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.8.15
      5: 0.13.9
      8:
      - 5
aggregation:
  desc: null
  value: max
apply_dropedge:
  desc: null
  value: true
apply_dropout:
  desc: null
  value: false
batch_size:
  desc: null
  value: 64
encoder_channels:
  desc: null
  value:
  - 64
epochs:
  desc: null
  value: 800
learning_rate:
  desc: null
  value: 0.0036722841150415497
num_hiddens:
  desc: null
  value: 64
num_layers:
  desc: null
  value: 6
num_skip_layers:
  desc: null
  value: 1
task:
  desc: null
  value: classification
weight_decay:
  desc: null
  value: 0.0001553675442114133
