wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value:
  - 128
epochs:
  value: 400
jk_mode:
  value: cat
learning_rate:
  value: 0.004429457230296779
num_hiddens:
  value: 32
num_layers:
  value: 8
task:
  value: regression
weight_decay:
  value: 0.008749857988625829
