wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value: []
epochs:
  value: 400
jk_mode:
  value: cat
learning_rate:
  value: 0.007297830511815923
num_hiddens:
  value: 16
num_layers:
  value: 10
task:
  value: regression
weight_decay:
  value: 0.0053354338285693855
