wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value:
  - 128
epochs:
  value: 400
jk_mode:
  value: lstm
learning_rate:
  value: 0.003194054339836924
num_hiddens:
  value: 32
num_layers:
  value: 6
task:
  value: regression
weight_decay:
  value: 0.008792646982305944
