wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value: []
epochs:
  value: 400
jk_mode:
  value: max
learning_rate:
  value: 0.0022376625908150597
num_hiddens:
  value: 16
num_layers:
  value: 10
task:
  value: regression
weight_decay:
  value: 0.0038184890454193137
