wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value:
  - 128
epochs:
  value: 400
jk_mode:
  value: cat
learning_rate:
  value: 0.007675620043360567
num_hiddens:
  value: 32
num_layers:
  value: 6
task:
  value: regression
weight_decay:
  value: 0.007501625762521588
