wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value:
  - 128
epochs:
  value: 400
jk_mode:
  value: lstm
learning_rate:
  value: 0.005337698639962918
num_hiddens:
  value: 16
num_layers:
  value: 4
task:
  value: regression
weight_decay:
  value: 0.003672817478042836
