wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value:
  - 128
epochs:
  value: 400
jk_mode:
  value: max
learning_rate:
  value: 0.006763810763451636
num_hiddens:
  value: 32
num_layers:
  value: 16
task:
  value: regression
weight_decay:
  value: 0.005870778759338033
