wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value: []
epochs:
  value: 400
jk_mode:
  value: max
learning_rate:
  value: 0.005111133825100752
num_hiddens:
  value: 64
num_layers:
  value: 6
task:
  value: regression
weight_decay:
  value: 0.002948358694608419
