wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value: []
epochs:
  value: 400
jk_mode:
  value: max
learning_rate:
  value: 0.0020518776564791134
num_hiddens:
  value: 32
num_layers:
  value: 6
task:
  value: regression
weight_decay:
  value: 0.007551668579530474
