wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value:
  - 128
epochs:
  value: 400
jk_mode:
  value: lstm
learning_rate:
  value: 0.004381033923644703
num_hiddens:
  value: 64
num_layers:
  value: 8
task:
  value: regression
weight_decay:
  value: 0.007335865452073296
