wandb_version: 1

aggregation:
  value: max
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value: 32
encoder_channels:
  value:
  - 128
epochs:
  value: 400
jk_mode:
  value: lstm
learning_rate:
  value: 0.005135410944815968
num_hiddens:
  value: 32
num_layers:
  value: 12
task:
  value: regression
weight_decay:
  value: 0.009671062860455784
