wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: true
batch_size:
  value: 32
encoder_channels:
  value:
  - 128
epochs:
  value: 400
jk_mode:
  value: max
learning_rate:
  value: 0.0023356660761255045
num_hiddens:
  value: 64
num_layers:
  value: 10
task:
  value: regression
weight_decay:
  value: 0.005661130900659646
