wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: false
apply_dropout:
  value: false
batch_size:
  value:
  - 16
  - 32
  - 64
encoder_channels:
  value: []
epochs:
  value: 800
learning_rate:
  value: 0.005456532023744592
num_hiddens:
  value: 64
num_layers:
  value: 4
num_skip_layers:
  value: 2
task:
  value: classification
weight_decay:
  value: 0.00973502882027696
