wandb_version: 1

aggregation:
  value: mean
apply_dropedge:
  value: true
apply_dropout:
  value: true
batch_size:
  value:
  - 16
  - 32
  - 64
encoder_channels:
  value:
  - 64
epochs:
  value: 800
learning_rate:
  value: 0.0030117345662212945
num_hiddens:
  value: 32
num_layers:
  value: 6
num_skip_layers:
  value: 2
task:
  value: classification
weight_decay:
  value: 0.003275567084559683
